/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const LOGIN_USER_DATA = "LOGIN_USER_DATA";



/* TODOAPP*/
export const TODO_GET_LIST = "TODO_GET_LIST";
export const TODO_GET_LIST_SUCCESS = "TODO_GET_LIST_SUCCESS";
export const TODO_GET_LIST_ERROR = "TODO_GET_LIST_ERROR";
export const TODO_GET_LIST_WITH_FILTER = "TODO_GET_LIST_WITH_FILTER";
export const TODO_GET_LIST_WITH_ORDER = "TODO_GET_LIST_WITH_ORDER";
export const TODO_GET_LIST_SEARCH = "TODO_GET_LIST_SEARCH";
export const TODO_ADD_ITEM = "TODO_ADD_ITEM";
export const TODO_ADD_ITEM_SUCCESS = "TODO_ADD_ITEM_SUCCESS";
export const TODO_ADD_ITEM_ERROR = "TODO_ADD_ITEM_ERROR";
export const TODO_SELECTED_ITEMS_CHANGE = "TODO_SELECTED_ITEMS_CHANGE";

/*religion*/
export const RELIGION_GET_LIST = "RELIGION_GET_LIST";
export const RELIGION_GET_LIST_SUCCESS = "RELIGION_GET_LIST_SUCCESS";
export const RELIGION_GET_LIST_ERROR = "RELIGION_GET_LIST_ERROR";
export const RELIGION_ADD_ITEM = "RELIGION_ADD_ITEM";
export const RELIGION_ADD_ITEM_SUCCESS = "RELIGION_ADD_ITEM_SUCCESS";
export const RELIGION_ADD_ITEM_ERROR = "RELIGION_ADD_ITEM_ERROR";
export const RELIGION_DELETE_ITEM = "RELIGION_DELETE_ITEM";
export const RELIGION_DELETE_SUCCESS = "RELIGION_DELETE_SUCCESS";
export const RELIGION_DELETE_ITEM_ERROR = "RELIGION_DELETE_ITEM_ERROR";
export const RELIGION_UPDATE_ITEM = "RELIGION_UPDATE_ITEM";
export const RELIGION_UPDATE_ITEM_SUCCESS = "RELIGION_UPDATE_ITEM_SUCCESS";
export const RELIGION_UPDATE_ITEM_ERROR = "RELIGION_UPDATE_ITEM_ERROR";
export const RELIGION_DELETE_CHECK = "RELIGION_DELETE_CHECK";







/*deduction */
export const DEDUCTION_GET_LIST = "DEDUCTION_GET_LIST";
export const DEDUCTION_GET_LIST_SUCCESS = "DEDUCTION_GET_LIST_SUCCESS";
export const DEDUCTION_GET_LIST_ERROR = "DEDUCTION_GET_LIST_ERROR";
export const DEDUCTION_ADD_ITEM = "DEDUCTION_ADD_ITEM";
export const DEDUCTION_ADD_ITEM_SUCCESS = "DEDUCTION_ADD_ITEM_SUCCESS";
export const DEDUCTION_ADD_ITEM_ERROR = "DEDUCTION_ADD_ITEM_ERROR";
export const DEDUCTION_DELETE_ITEM = "DEDUCTION_DELETE_ITEM";
export const DEDUCTION_DELETE_SUCCESS = "DEDUCTION_DELETE_SUCCESS";
export const DEDUCTION_DELETE_ITEM_ERROR = "DEDUCTION_DELETE_ITEM_ERROR";
export const DEDUCTION_UPDATE_ITEM = "DEDUCTION_UPDATE_ITEM";
export const DEDUCTION_UPDATE_ITEM_SUCCESS = "DEDUCTION_UPDATE_ITEM_SUCCESS";
export const DEDUCTION_UPDATE_ITEM_ERROR = "DEDUCTION_UPDATE_ITEM_ERROR";
export const DEDUCTION_DELETE_CHECK = "DEDUCTION_DELETE_CHECK";

/*modification type */
export const MODIFICATIONTYPE_GET_LIST = "MODIFICATIONTYPE_GET_LIST";
export const MODIFICATIONTYPE_GET_LIST_SUCCESS = "MODIFICATIONTYPE_GET_LIST_SUCCESS";
export const MODIFICATIONTYPE_GET_LIST_ERROR = "MODIFICATIONTYPE_GET_LIST_ERROR";
export const MODIFICATIONTYPE_ADD_ITEM = "MODIFICATIONTYPE_ADD_ITEM";
export const MODIFICATIONTYPE_ADD_ITEM_SUCCESS = "MODIFICATIONTYPE_ADD_ITEM_SUCCESS";
export const MODIFICATIONTYPE_ADD_ITEM_ERROR = "MODIFICATIONTYPE_ADD_ITEM_ERROR";
export const MODIFICATIONTYPE_DELETE_ITEM = "MODIFICATIONTYPE_DELETE_ITEM";
export const MODIFICATIONTYPE_DELETE_SUCCESS = "MODIFICATIONTYPE_DELETE_SUCCESS";
export const MODIFICATIONTYPE_DELETE_ITEM_ERROR = "MODIFICATIONTYPE_DELETE_ITEM_ERROR";
export const MODIFICATIONTYPE_UPDATE_ITEM = "MODIFICATIONTYPE_UPDATE_ITEM";
export const MODIFICATIONTYPE_UPDATE_ITEM_SUCCESS = "MODIFICATIONTYPE_UPDATE_ITEM_SUCCESS";
export const MODIFICATIONTYPE_UPDATE_ITEM_ERROR = "MODIFICATIONTYPE_UPDATE_ITEM_ERROR";
export const MODIFICATIONTYPE_DELETE_CHECK = "MODIFICATIONTYPE_DELETE_CHECK";

/*currencies type */
export const CURRENCIESTYPE_GET_LIST = " CURRENCIESTYPE_GET_LIST";
export const CURRENCIESTYPE_GET_LIST_SUCCESS = " CURRENCIESTYPE_GET_LIST_SUCCESS";
export const CURRENCIESTYPE_GET_LIST_ERROR = " CURRENCIESTYPE_GET_LIST_ERROR";
export const CURRENCIESTYPE_ADD_ITEM = " CURRENCIESTYPE_ADD_ITEM";
export const CURRENCIESTYPE_ADD_ITEM_SUCCESS = " CURRENCIESTYPE_ADD_ITEM_SUCCESS";
export const CURRENCIESTYPE_ADD_ITEM_ERROR = " CURRENCIESTYPE_ADD_ITEM_ERROR";
export const CURRENCIESTYPE_DELETE_ITEM = " CURRENCIESTYPE_DELETE_ITEM";
export const CURRENCIESTYPE_DELETE_SUCCESS = " CURRENCIESTYPE_DELETE_SUCCESS";
export const CURRENCIESTYPE_DELETE_ITEM_ERROR = " CURRENCIESTYPE_DELETE_ITEM_ERROR";
export const CURRENCIESTYPE_UPDATE_ITEM = " CURRENCIESTYPE_UPDATE_ITEM";
export const CURRENCIESTYPE_UPDATE_ITEM_SUCCESS = " CURRENCIESTYPE_UPDATE_ITEM_SUCCESS";
export const CURRENCIESTYPE_UPDATE_ITEM_ERROR = " CURRENCIESTYPE_UPDATE_ITEM_ERROR";
export const CURRENCIESTYPE_DELETE_CHECK = " CURRENCIESTYPE_DELETE_CHECK";

/*section */
export const SECTION_GET_LIST = " SECTION_GET_LIST";
export const SECTION_GET_LIST_SUCCESS = " SECTION_GET_LIST_SUCCESS";
export const SECTION_GET_LIST_ERROR = " SECTION_GET_LIST_ERROR";
export const SECTION_ADD_ITEM = " SECTION_ADD_ITEM";
export const SECTION_ADD_ITEM_SUCCESS = " SECTION_ADD_ITEM_SUCCESS";
export const SECTION_ADD_ITEM_ERROR = " SECTION_ADD_ITEM_ERROR";
export const SECTION_DELETE_ITEM = " SECTION_DELETE_ITEM";
export const SECTION_DELETE_SUCCESS = " SECTION_DELETE_SUCCESS";
export const SECTION_DELETE_ITEM_ERROR = " SECTION_DELETE_ITEM_ERROR";
export const SECTION_UPDATE_ITEM = " SECTION_UPDATE_ITEM";
export const SECTION_UPDATE_ITEM_SUCCESS = " SECTION_UPDATE_ITEM_SUCCESS";
export const SECTION_UPDATE_ITEM_ERROR = " SECTION_UPDATE_ITEM_ERROR";
export const SECTION_DELETE_CHECK = " SECTION_DELETE_CHECK";


/*cost center*/
export const COSTCENTER_GET_LIST = " COSTCENTER_GET_LIST";
export const COSTCENTER_GET_LIST_SUCCESS = " COSTCENTER_GET_LIST_SUCCESS";
export const COSTCENTER_GET_LIST_ERROR = " COSTCENTER_GET_LIST_ERROR";
export const COSTCENTER_ADD_ITEM = " COSTCENTER_ADD_ITEM";
export const COSTCENTER_ADD_ITEM_SUCCESS = " COSTCENTER_ADD_ITEM_SUCCESS";
export const COSTCENTER_ADD_ITEM_ERROR = " COSTCENTER_ADD_ITEM_ERROR";
export const COSTCENTER_DELETE_ITEM = " COSTCENTER_DELETE_ITEM";
export const COSTCENTER_DELETE_SUCCESS = " COSTCENTER_DELETE_SUCCESS";
export const COSTCENTER_DELETE_ITEM_ERROR = " COSTCENTER_DELETE_ITEM_ERROR";
export const COSTCENTER_UPDATE_ITEM = " COSTCENTER_UPDATE_ITEM";
export const COSTCENTER_UPDATE_ITEM_SUCCESS = " COSTCENTER_UPDATE_ITEM_SUCCESS";
export const COSTCENTER_UPDATE_ITEM_ERROR = " COSTCENTER_UPDATE_ITEM_ERROR";
export const COSTCENTER_DELETE_CHECK = " COSTCENTER_DELETE_CHECK";

/*percentage*/
export const PERCENTAGE_GET_LIST = " PERCENTAGE_GET_LIST";
export const PERCENTAGE_GET_LIST_SUCCESS = " PERCENTAGE_GET_LIST_SUCCESS";
export const PERCENTAGE_GET_LIST_ERROR = " PERCENTAGE_GET_LIST_ERROR";
export const PERCENTAGE_ADD_ITEM = " PERCENTAGE_ADD_ITEM";
export const PERCENTAGE_ADD_ITEM_SUCCESS = " PERCENTAGE_ADD_ITEM_SUCCESS";
export const PERCENTAGE_ADD_ITEM_ERROR = " PERCENTAGE_ADD_ITEM_ERROR";
export const PERCENTAGE_DELETE_ITEM = " PERCENTAGE_DELETE_ITEM";
export const PERCENTAGE_DELETE_SUCCESS = " PERCENTAGE_DELETE_SUCCESS";
export const PERCENTAGE_DELETE_ITEM_ERROR = " PERCENTAGE_DELETE_ITEM_ERROR";
export const PERCENTAGE_UPDATE_ITEM = " PERCENTAGE_UPDATE_ITEM";
export const PERCENTAGE_UPDATE_ITEM_SUCCESS = " PERCENTAGE_UPDATE_ITEM_SUCCESS";
export const PERCENTAGE_UPDATE_ITEM_ERROR = " PERCENTAGE_UPDATE_ITEM_ERROR";
export const PERCENTAGE_DELETE_CHECK = " PERCENTAGE_DELETE_CHECK";


/*beneficiary type*/
export const BENEFICIARY_TYPE_GET_LIST = "BENEFICIARY_TYPE_GET_LIST";
export const BENEFICIARY_TYPE_GET_LIST_SUCCESS =
  "BENEFICIARY_TYPE_GET_LIST_SUCCESS";
export const BENEFICIARY_TYPE_GET_LIST_ERROR =
  "BENEFICIARY_TYPE_GET_LIST_ERROR";
export const BENEFICIARY_TYPE_ADD_ITEM = "BENEFICIARY_TYPE_ADD_ITEM";
export const BENEFICIARY_TYPE_ADD_ITEM_SUCCESS =
  "BENEFICIARY_TYPE_ADD_ITEM_SUCCESS";
export const BENEFICIARY_TYPE_ADD_ITEM_ERROR =
  "BENEFICIARY_TYPE_ADD_ITEM_ERROR";
export const BENEFICIARY_TYPE_DELETE_ITEM = "BENEFICIARY_TYPE_DELETE_ITEM";
export const BENEFICIARY_TYPE_DELETE_SUCCESS =
  "BENEFICIARY_TYPE_DELETE_SUCCESS";
export const BENEFICIARY_TYPE_DELETE_ITEM_ERROR =
  "BENEFICIARY_TYPE_DELETE_ITEM_ERROR";
export const BENEFICIARY_TYPE_UPDATE_ITEM = "BENEFICIARY_TYPE_UPDATE_ITEM";
export const BENEFICIARY_TYPE_UPDATE_ITEM_SUCCESS =
  "BENEFICIARY_TYPE_UPDATE_ITEM_SUCCESS";
export const BENEFICIARY_TYPE_UPDATE_ITEM_ERROR =
  "BENEFICIARY_TYPE_UPDATE_ITEM_ERROR";
export const BENEFICIARY_TYPE_DELETE_CHECK = "BENEFICIARY_TYPE_DELETE_CHECK";

/*leave vacation type*/
export const LEAVEVACATIONTYPE_GET_LIST = "LEAVEVACATIONTYPE_GET_LIST";
export const LEAVEVACATIONTYPE_GET_LIST_SUCCESS =
  "LEAVEVACATIONTYPE_GET_LIST_SUCCESS";
export const LEAVEVACATIONTYPE_GET_LIST_ERROR =
  "LEAVEVACATIONTYPE_GET_LIST_ERROR";
export const LEAVEVACATIONTYPE_ADD_ITEM = "LEAVEVACATIONTYPE_ADD_ITEM";
export const LEAVEVACATIONTYPE_ADD_ITEM_SUCCESS =
  "LEAVEVACATIONTYPE_ADD_ITEM_SUCCESS";
export const LEAVEVACATIONTYPE_ADD_ITEM_ERROR =
  "LEAVEVACATIONTYPE_ADD_ITEM_ERROR";
export const LEAVEVACATIONTYPE_DELETE_ITEM = "LEAVEVACATIONTYPE_DELETE_ITEM";
export const LEAVEVACATIONTYPE_DELETE_SUCCESS =
  "LEAVEVACATIONTYPE_DELETE_SUCCESS";
export const LEAVEVACATIONTYPE_DELETE_ITEM_ERROR =
  "LEAVEVACATIONTYPE_DELETE_ITEM_ERROR";
export const LEAVEVACATIONTYPE_UPDATE_ITEM = "LEAVEVACATIONTYPE_UPDATE_ITEM";
export const LEAVEVACATIONTYPE_UPDATE_ITEM_SUCCESS =
  "LEAVEVACATIONTYPE_UPDATE_ITEM_SUCCESS";
export const LEAVEVACATIONTYPE_UPDATE_ITEM_ERROR =
  "LEAVEVACATIONTYPE_UPDATE_ITEM_ERROR";
export const LEAVEVACATIONTYPE_DELETE_CHECK = "LEAVEVACATIONTYPE_DELETE_CHECK";

/*position designation*/
export const POSITIONDESIGNATION_GET_LIST = "POSITIONDESIGNATION_GET_LIST";
export const POSITIONDESIGNATION_GET_LIST_SUCCESS =
  "POSITIONDESIGNATION_GET_LIST_SUCCESS";
export const POSITIONDESIGNATION_GET_LIST_ERROR =
  "POSITIONDESIGNATION_GET_LIST_ERROR";
export const POSITIONDESIGNATION_ADD_ITEM = "POSITIONDESIGNATION_ADD_ITEM";
export const POSITIONDESIGNATION_ADD_ITEM_SUCCESS =
  "POSITIONDESIGNATION_ADD_ITEM_SUCCESS";
export const POSITIONDESIGNATION_ADD_ITEM_ERROR =
  "POSITIONDESIGNATION_ADD_ITEM_ERROR";
export const POSITIONDESIGNATION_DELETE_ITEM =
  "POSITIONDESIGNATION_DELETE_ITEM";
export const POSITIONDESIGNATION_DELETE_SUCCESS =
  "POSITIONDESIGNATION_DELETE_SUCCESS";
export const POSITIONDESIGNATION_DELETE_ITEM_ERROR =
  "POSITIONDESIGNATION_DELETE_ITEM_ERROR";
export const POSITIONDESIGNATION_UPDATE_ITEM =
  "POSITIONDESIGNATION_UPDATE_ITEM";
export const POSITIONDESIGNATION_UPDATE_ITEM_SUCCESS =
  "POSITIONDESIGNATION_UPDATE_ITEM_SUCCESS";
export const POSITIONDESIGNATION_UPDATE_ITEM_ERROR =
  "POSITIONDESIGNATION_UPDATE_ITEM_ERROR";
export const POSITIONDESIGNATION_DELETE_CHECK =
  "POSITIONDESIGNATION_DELETE_CHECK";

/*sponsor */
export const SPONSOR_GET_LIST = "SPONSOR_GET_LIST";
export const SPONSOR_GET_LIST_SUCCESS = "SPONSOR_GET_LIST_SUCCESS";
export const SPONSOR_GET_LIST_ERROR = "SPONSOR_GET_LIST_ERROR";
export const SPONSOR_ADD_ITEM = "SPONSOR_ADD_ITEM";
export const SPONSOR_ADD_ITEM_SUCCESS = "SPONSOR_ADD_ITEM_SUCCESS";
export const SPONSOR_ADD_ITEM_ERROR = "SPONSOR_ADD_ITEM_ERROR";
export const SPONSOR_DELETE_ITEM = "SPONSOR_DELETE_ITEM";
export const SPONSOR_DELETE_SUCCESS = "SPONSOR_DELETE_SUCCESS";
export const SPONSOR_DELETE_ITEM_ERROR = "SPONSOR_DELETE_ITEM_ERROR";
export const SPONSOR_UPDATE_ITEM = "SPONSOR_UPDATE_ITEM";
export const SPONSOR_UPDATE_ITEM_SUCCESS = "SPONSOR_UPDATE_ITEM_SUCCESS";
export const SPONSOR_UPDATE_ITEM_ERROR = "SPONSOR_UPDATE_ITEM_ERROR";
export const SPONSOR_DELETE_CHECK = "SPONSOR_DELETE_CHECK";

/*earnings benefits */
export const EARNINGSBENEFITS_GET_LIST = "EARNINGSBENEFITS_GET_LIST";
export const EARNINGSBENEFITS_GET_LIST_SUCCESS =
  "EARNINGSBENEFITS_GET_LIST_SUCCESS";
export const EARNINGSBENEFITS_GET_LIST_ERROR =
  "EARNINGSBENEFITS_GET_LIST_ERROR";
export const EARNINGSBENEFITS_ADD_ITEM = "EARNINGSBENEFITS_ADD_ITEM";
export const EARNINGSBENEFITS_ADD_ITEM_SUCCESS =
  "EARNINGSBENEFITS_ADD_ITEM_SUCCESS";
export const EARNINGSBENEFITS_ADD_ITEM_ERROR =
  "EARNINGSBENEFITS_ADD_ITEM_ERROR";
export const EARNINGSBENEFITS_DELETE_ITEM = "EARNINGSBENEFITS_DELETE_ITEM";
export const EARNINGSBENEFITS_DELETE_SUCCESS =
  "EARNINGSBENEFITS_DELETE_SUCCESS";
export const EARNINGSBENEFITS_DELETE_ITEM_ERROR =
  "EARNINGSBENEFITS_DELETE_ITEM_ERROR";
export const EARNINGSBENEFITS_UPDATE_ITEM = "EARNINGSBENEFITS_UPDATE_ITEM";
export const EARNINGSBENEFITS_UPDATE_ITEM_SUCCESS =
  "EARNINGSBENEFITS_UPDATE_ITEM_SUCCESS";
export const EARNINGSBENEFITS_UPDATE_ITEM_ERROR =
  "EARNINGSBENEFITS_UPDATE_ITEM_ERROR";
export const EARNINGSBENEFITS_DELETE_CHECK = "EARNINGSBENEFITS_DELETE_CHECK";

/*deduction */
export const DEDUCTION_GET_LIST = "DEDUCTION_GET_LIST";
export const DEDUCTION_GET_LIST_SUCCESS = "DEDUCTION_GET_LIST_SUCCESS";
export const DEDUCTION_GET_LIST_ERROR = "DEDUCTION_GET_LIST_ERROR";
export const DEDUCTION_ADD_ITEM = "DEDUCTION_ADD_ITEM";
export const DEDUCTION_ADD_ITEM_SUCCESS = "DEDUCTION_ADD_ITEM_SUCCESS";
export const DEDUCTION_ADD_ITEM_ERROR = "DEDUCTION_ADD_ITEM_ERROR";
export const DEDUCTION_DELETE_ITEM = "DEDUCTION_DELETE_ITEM";
export const DEDUCTION_DELETE_SUCCESS = "DEDUCTION_DELETE_SUCCESS";
export const DEDUCTION_DELETE_ITEM_ERROR = "DEDUCTION_DELETE_ITEM_ERROR";
export const DEDUCTION_UPDATE_ITEM = "DEDUCTION_UPDATE_ITEM";
export const DEDUCTION_UPDATE_ITEM_SUCCESS = "DEDUCTION_UPDATE_ITEM_SUCCESS";
export const DEDUCTION_UPDATE_ITEM_ERROR = "DEDUCTION_UPDATE_ITEM_ERROR";
export const DEDUCTION_DELETE_CHECK = "DEDUCTION_DELETE_CHECK";

/*modification type */
export const MODIFICATIONTYPE_GET_LIST = "MODIFICATIONTYPE_GET_LIST";
export const MODIFICATIONTYPE_GET_LIST_SUCCESS =
  "MODIFICATIONTYPE_GET_LIST_SUCCESS";
export const MODIFICATIONTYPE_GET_LIST_ERROR =
  "MODIFICATIONTYPE_GET_LIST_ERROR";
export const MODIFICATIONTYPE_ADD_ITEM = "MODIFICATIONTYPE_ADD_ITEM";
export const MODIFICATIONTYPE_ADD_ITEM_SUCCESS =
  "MODIFICATIONTYPE_ADD_ITEM_SUCCESS";
export const MODIFICATIONTYPE_ADD_ITEM_ERROR =
  "MODIFICATIONTYPE_ADD_ITEM_ERROR";
export const MODIFICATIONTYPE_DELETE_ITEM = "MODIFICATIONTYPE_DELETE_ITEM";
export const MODIFICATIONTYPE_DELETE_SUCCESS =
  "MODIFICATIONTYPE_DELETE_SUCCESS";
export const MODIFICATIONTYPE_DELETE_ITEM_ERROR =
  "MODIFICATIONTYPE_DELETE_ITEM_ERROR";
export const MODIFICATIONTYPE_UPDATE_ITEM = "MODIFICATIONTYPE_UPDATE_ITEM";
export const MODIFICATIONTYPE_UPDATE_ITEM_SUCCESS =
  "MODIFICATIONTYPE_UPDATE_ITEM_SUCCESS";
export const MODIFICATIONTYPE_UPDATE_ITEM_ERROR =
  "MODIFICATIONTYPE_UPDATE_ITEM_ERROR";
export const MODIFICATIONTYPE_DELETE_CHECK = "MODIFICATIONTYPE_DELETE_CHECK";

/*currencies type */
export const CURRENCIESTYPE_GET_LIST = " CURRENCIESTYPE_GET_LIST";
export const CURRENCIESTYPE_GET_LIST_SUCCESS =
  " CURRENCIESTYPE_GET_LIST_SUCCESS";
export const CURRENCIESTYPE_GET_LIST_ERROR = " CURRENCIESTYPE_GET_LIST_ERROR";
export const CURRENCIESTYPE_ADD_ITEM = " CURRENCIESTYPE_ADD_ITEM";
export const CURRENCIESTYPE_ADD_ITEM_SUCCESS =
  " CURRENCIESTYPE_ADD_ITEM_SUCCESS";
export const CURRENCIESTYPE_ADD_ITEM_ERROR = " CURRENCIESTYPE_ADD_ITEM_ERROR";
export const CURRENCIESTYPE_DELETE_ITEM = " CURRENCIESTYPE_DELETE_ITEM";
export const CURRENCIESTYPE_DELETE_SUCCESS = " CURRENCIESTYPE_DELETE_SUCCESS";
export const CURRENCIESTYPE_DELETE_ITEM_ERROR =
  " CURRENCIESTYPE_DELETE_ITEM_ERROR";
export const CURRENCIESTYPE_UPDATE_ITEM = " CURRENCIESTYPE_UPDATE_ITEM";
export const CURRENCIESTYPE_UPDATE_ITEM_SUCCESS =
  " CURRENCIESTYPE_UPDATE_ITEM_SUCCESS";
export const CURRENCIESTYPE_UPDATE_ITEM_ERROR =
  " CURRENCIESTYPE_UPDATE_ITEM_ERROR";
export const CURRENCIESTYPE_DELETE_CHECK = " CURRENCIESTYPE_DELETE_CHECK";

/*section */
export const SECTION_GET_LIST = " SECTION_GET_LIST";
export const SECTION_GET_LIST_SUCCESS = " SECTION_GET_LIST_SUCCESS";
export const SECTION_GET_LIST_ERROR = " SECTION_GET_LIST_ERROR";
export const SECTION_ADD_ITEM = " SECTION_ADD_ITEM";
export const SECTION_ADD_ITEM_SUCCESS = " SECTION_ADD_ITEM_SUCCESS";
export const SECTION_ADD_ITEM_ERROR = " SECTION_ADD_ITEM_ERROR";
export const SECTION_DELETE_ITEM = " SECTION_DELETE_ITEM";
export const SECTION_DELETE_SUCCESS = " SECTION_DELETE_SUCCESS";
export const SECTION_DELETE_ITEM_ERROR = " SECTION_DELETE_ITEM_ERROR";
export const SECTION_UPDATE_ITEM = " SECTION_UPDATE_ITEM";
export const SECTION_UPDATE_ITEM_SUCCESS = " SECTION_UPDATE_ITEM_SUCCESS";
export const SECTION_UPDATE_ITEM_ERROR = " SECTION_UPDATE_ITEM_ERROR";
export const SECTION_DELETE_CHECK = " SECTION_DELETE_CHECK";

/*cost center*/
export const COSTCENTER_GET_LIST = " COSTCENTER_GET_LIST";
export const COSTCENTER_GET_LIST_SUCCESS = " COSTCENTER_GET_LIST_SUCCESS";
export const COSTCENTER_GET_LIST_ERROR = " COSTCENTER_GET_LIST_ERROR";
export const COSTCENTER_ADD_ITEM = " COSTCENTER_ADD_ITEM";
export const COSTCENTER_ADD_ITEM_SUCCESS = " COSTCENTER_ADD_ITEM_SUCCESS";
export const COSTCENTER_ADD_ITEM_ERROR = " COSTCENTER_ADD_ITEM_ERROR";
export const COSTCENTER_DELETE_ITEM = " COSTCENTER_DELETE_ITEM";
export const COSTCENTER_DELETE_SUCCESS = " COSTCENTER_DELETE_SUCCESS";
export const COSTCENTER_DELETE_ITEM_ERROR = " COSTCENTER_DELETE_ITEM_ERROR";
export const COSTCENTER_UPDATE_ITEM = " COSTCENTER_UPDATE_ITEM";
export const COSTCENTER_UPDATE_ITEM_SUCCESS = " COSTCENTER_UPDATE_ITEM_SUCCESS";
export const COSTCENTER_UPDATE_ITEM_ERROR = " COSTCENTER_UPDATE_ITEM_ERROR";
export const COSTCENTER_DELETE_CHECK = " COSTCENTER_DELETE_CHECK";

/*percentage*/
export const PERCENTAGE_GET_LIST = " PERCENTAGE_GET_LIST";
export const PERCENTAGE_GET_LIST_SUCCESS = " PERCENTAGE_GET_LIST_SUCCESS";
export const PERCENTAGE_GET_LIST_ERROR = " PERCENTAGE_GET_LIST_ERROR";
export const PERCENTAGE_ADD_ITEM = " PERCENTAGE_ADD_ITEM";
export const PERCENTAGE_ADD_ITEM_SUCCESS = " PERCENTAGE_ADD_ITEM_SUCCESS";
export const PERCENTAGE_ADD_ITEM_ERROR = " PERCENTAGE_ADD_ITEM_ERROR";
export const PERCENTAGE_DELETE_ITEM = " PERCENTAGE_DELETE_ITEM";
export const PERCENTAGE_DELETE_SUCCESS = " PERCENTAGE_DELETE_SUCCESS";
export const PERCENTAGE_DELETE_ITEM_ERROR = " PERCENTAGE_DELETE_ITEM_ERROR";
export const PERCENTAGE_UPDATE_ITEM = " PERCENTAGE_UPDATE_ITEM";
export const PERCENTAGE_UPDATE_ITEM_SUCCESS = " PERCENTAGE_UPDATE_ITEM_SUCCESS";
export const PERCENTAGE_UPDATE_ITEM_ERROR = " PERCENTAGE_UPDATE_ITEM_ERROR";
export const PERCENTAGE_DELETE_CHECK = " PERCENTAGE_DELETE_CHECK";
/*evaluation types*/
export const EVALUATIONTYPE_GET_LIST = "EVALUATIONTYPE_GET_LIST";
export const EVALUATIONTYPE_GET_LIST_SUCCESS =
  "EVALUATIONTYPE_GET_LIST_SUCCESS";
export const EVALUATIONTYPE_GET_LIST_ERROR = "EVALUATIONTYPE_GET_LIST_ERROR";
export const EVALUATIONTYPE_ADD_ITEM = "EVALUATIONTYPE_ADD_ITEM";
export const EVALUATIONTYPE_ADD_ITEM_SUCCESS =
  "EVALUATIONTYPE_ADD_ITEM_SUCCESS";
export const EVALUATIONTYPE_ADD_ITEM_ERROR = "EVALUATIONTYPE_ADD_ITEM_ERROR";
export const EVALUATIONTYPE_DELETE_ITEM = "EVALUATIONTYPE_DELETE_ITEM";
export const EVALUATIONTYPE_DELETE_SUCCESS = "EVALUATIONTYPE_DELETE_SUCCESS";
export const EVALUATIONTYPE_DELETE_ITEM_ERROR =
  "EVALUATIONTYPE_DELETE_ITEM_ERROR";
export const EVALUATIONTYPE_UPDATE_ITEM = "EVALUATIONTYPE_UPDATE_ITEM";
export const EVALUATIONTYPE_UPDATE_ITEM_SUCCESS =
  "EVALUATIONTYPE_UPDATE_ITEM_SUCCESS";
export const EVALUATIONTYPE_UPDATE_ITEM_ERROR =
  "EVALUATIONTYPE_UPDATE_ITEM_ERROR";
export const EVALUATIONTYPE_DELETE_CHECK = "EVALUATIONTYPE_DELETE_CHECK";

/*SESSION*/
export const SESSION_GET_LIST = "SESSION_GET_LIST";
export const SESSION_GET_LIST_SUCCESS = "SESSION_GET_LIST_SUCCESS";
export const SESSION_GET_LIST_ERROR = "SESSION_GET_LIST_ERROR";
export const SESSION_ADD_ITEM = "SESSION_ADD_ITEM";
export const SESSION_ADD_ITEM_SUCCESS = "SESSION_ADD_ITEM_SUCCESS";
export const SESSION_ADD_ITEM_ERROR = "SESSION_ADD_ITEM_ERROR";
export const SESSION_DELETE_ITEM = "SESSION_DELETE_ITEM";
export const SESSION_DELETE_SUCCESS = "SESSION_DELETE_SUCCESS";
export const SESSION_DELETE_ITEM_ERROR = "SESSION_DELETE_ITEM_ERROR";
export const SESSION_UPDATE_ITEM = "SESSION_UPDATE_ITEM";
export const SESSION_UPDATE_ITEM_SUCCESS = "SESSION_UPDATE_ITEM_SUCCESS";
export const SESSION_UPDATE_ITEM_ERROR = "SESSION_UPDATE_ITEM_ERROR";
export const SESSION_DELETE_CHECK = "SESSION_DELETE_CHECK";

/*COMPANYSCHEDULE*/
export const COMPANYSCHEDULE_GET_LIST = "COMPANYSCHEDULE_GET_LIST";
export const COMPANYSCHEDULE_GET_LIST_SUCCESS =
  "COMPANYSCHEDULE_GET_LIST_SUCCESS";
export const COMPANYSCHEDULE_GET_LIST_ERROR = "COMPANYSCHEDULE_GET_LIST_ERROR";
export const COMPANYSCHEDULE_ADD_ITEM = "COMPANYSCHEDULE_ADD_ITEM";
export const COMPANYSCHEDULE_ADD_ITEM_SUCCESS =
  "COMPANYSCHEDULE_ADD_ITEM_SUCCESS";
export const COMPANYSCHEDULE_ADD_ITEM_ERROR = "COMPANYSCHEDULE_ADD_ITEM_ERROR";
export const COMPANYSCHEDULE_DELETE_ITEM = "COMPANYSCHEDULE_DELETE_ITEM";
export const COMPANYSCHEDULE_DELETE_SUCCESS = "COMPANYSCHEDULE_DELETE_SUCCESS";
export const COMPANYSCHEDULE_DELETE_ITEM_ERROR =
  "COMPANYSCHEDULE_DELETE_ITEM_ERROR";
export const COMPANYSCHEDULE_UPDATE_ITEM = "COMPANYSCHEDULE_UPDATE_ITEM";
export const COMPANYSCHEDULE_UPDATE_ITEM_SUCCESS =
  "COMPANYSCHEDULE_UPDATE_ITEM_SUCCESS";
export const COMPANYSCHEDULE_UPDATE_ITEM_ERROR =
  "COMPANYSCHEDULE_UPDATE_ITEM_ERROR";
export const COMPANYSCHEDULE_DELETE_CHECK = "COMPANYSCHEDULE_DELETE_CHECK";

/*GOSISUBSCRIPTION*/
export const GOSISUBSCRIPTION_GET_LIST = "GOSISUBSCRIPTION_GET_LIST";
export const GOSISUBSCRIPTION_GET_LIST_SUCCESS =
  "GOSISUBSCRIPTION_GET_LIST_SUCCESS";
export const GOSISUBSCRIPTION_GET_LIST_ERROR =
  "GOSISUBSCRIPTION_GET_LIST_ERROR";
export const GOSISUBSCRIPTION_ADD_ITEM = "GOSISUBSCRIPTION_ADD_ITEM";
export const GOSISUBSCRIPTION_ADD_ITEM_SUCCESS =
  "GOSISUBSCRIPTION_ADD_ITEM_SUCCESS";
export const GOSISUBSCRIPTION_ADD_ITEM_ERROR =
  "GOSISUBSCRIPTION_ADD_ITEM_ERROR";
export const GOSISUBSCRIPTION_DELETE_ITEM = "GOSISUBSCRIPTION_DELETE_ITEM";
export const GOSISUBSCRIPTION_DELETE_SUCCESS =
  "GOSISUBSCRIPTION_DELETE_SUCCESS";
export const GOSISUBSCRIPTION_DELETE_ITEM_ERROR =
  "GOSISUBSCRIPTION_DELETE_ITEM_ERROR";
export const GOSISUBSCRIPTION_UPDATE_ITEM = "GOSISUBSCRIPTION_UPDATE_ITEM";
export const GOSISUBSCRIPTION_UPDATE_ITEM_SUCCESS =
  "GOSISUBSCRIPTION_UPDATE_ITEM_SUCCESS";
export const GOSISUBSCRIPTION_UPDATE_ITEM_ERROR =
  "GOSISUBSCRIPTION_UPDATE_ITEM_ERROR";
export const GOSISUBSCRIPTION_DELETE_CHECK = "GOSISUBSCRIPTION_DELETE_CHECK";

export * from "./menu/actions";
export * from "./settings/actions";

export * from "./auth/actions";
export * from "./religion/actions";

<<<<<<< HEAD
export * from "./evaluationcompentencies/actions";
export * from "./educationtrainingtype/actions";
export * from "./documenttype/actions";
export * from "./beneficiary_type/actions";
export * from "./leave_vacation_type/actions";
export * from "./position_designation/actions";
export * from "./sponsor/actions";
export * from "./earningsbenefits/actions";

=======
>>>>>>> 8cc52ae9c904d845c89cf2caecba6273662488dd
export * from "./deduction/actions";
export * from "./modification_type/actions";
export * from "./currencies_type/actions";
export * from "./section/actions";
export * from "./costcenter/actions";
export * from "./percentage/actions";
<<<<<<< HEAD
export * from "./evaluationtype/actions";
export * from "./session/actions";
export * from "./companyschedule/actions";
export * from "./gosisubscription/actions";
=======

// export * from "./documenttype/actions";
>>>>>>> 8cc52ae9c904d845c89cf2caecba6273662488dd
