/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const LOGIN_USER_DATA = "LOGIN_USER_DATA";

/*Country*/
export const COUNTRY_GET_LIST = "COUNTRY_GET_LIST";
export const COUNTRY_GET_LIST_SUCCESS = "COUNTRY_GET_LIST_SUCCESS";
export const COUNTRY_GET_LIST_ERROR = "COUNTRY_GET_LIST_ERROR";
export const COUNTRY_ADD_ITEM = "COUNTRY_ADD_ITEM";
export const COUNTRY_ADD_ITEM_SUCCESS = "COUNTRY_ADD_ITEM_SUCCESS";
export const COUNTRY_ADD_ITEM_ERROR = "COUNTRY_ADD_ITEM_ERROR";
export const COUNTRY_DELETE_ITEM = "COUNTRY_DELETE_ITEM";
export const COUNTRY_DELETE_SUCCESS = "COUNTRY_DELETE_SUCCESS";
export const COUNTRY_DELETE_ITEM_ERROR = "COUNTRY_DELETE_ITEM_ERROR";
export const COUNTRY_UPDATE_ITEM = "COUNTRY_UPDATE_ITEM";
export const COUNTRY_UPDATE_ITEM_SUCCESS = "COUNTRY_UPDATE_ITEM_SUCCESS";
export const COUNTRY_UPDATE_ITEM_ERROR = "COUNTRY_UPDATE_ITEM_ERROR";
export const COUNTRY_DELETE_CHECK = "COUNTRY_DELETE_CHECK";
/*Country*/
export const CITY_GET_LIST = "CITY_GET_LIST";
export const CITY_GET_LIST_SUCCESS = "CITY_GET_LIST_SUCCESS";
export const CITY_GET_LIST_ERROR = "CITY_GET_LIST_ERROR";
export const CITY_ADD_ITEM = "CITY_ADD_ITEM";
export const CITY_ADD_ITEM_SUCCESS = "CITY_ADD_ITEM_SUCCESS";
export const CITY_ADD_ITEM_ERROR = "CITY_ADD_ITEM_ERROR";
export const CITY_DELETE_ITEM = "CITY_DELETE_ITEM";
export const CITY_DELETE_SUCCESS = "CITY_DELETE_SUCCESS";
export const CITY_DELETE_ITEM_ERROR = "CITY_DELETE_ITEM_ERROR";
export const CITY_UPDATE_ITEM = "CITY_UPDATE_ITEM";
export const CITY_UPDATE_ITEM_SUCCESS = "CITY_UPDATE_ITEM_SUCCESS";
export const CITY_UPDATE_ITEM_ERROR = "CITY_UPDATE_ITEM_ERROR";
export const CITY_DELETE_CHECK = "CITY_DELETE_CHECK";

/* TODOAPP*/
export const TODO_GET_LIST = "TODO_GET_LIST";
export const TODO_GET_LIST_SUCCESS = "TODO_GET_LIST_SUCCESS";
export const TODO_GET_LIST_ERROR = "TODO_GET_LIST_ERROR";
export const TODO_GET_LIST_WITH_FILTER = "TODO_GET_LIST_WITH_FILTER";
export const TODO_GET_LIST_WITH_ORDER = "TODO_GET_LIST_WITH_ORDER";
export const TODO_GET_LIST_SEARCH = "TODO_GET_LIST_SEARCH";
export const TODO_ADD_ITEM = "TODO_ADD_ITEM";
export const TODO_ADD_ITEM_SUCCESS = "TODO_ADD_ITEM_SUCCESS";
export const TODO_ADD_ITEM_ERROR = "TODO_ADD_ITEM_ERROR";
export const TODO_SELECTED_ITEMS_CHANGE = "TODO_SELECTED_ITEMS_CHANGE";

export * from "./menu/actions";
export * from "./settings/actions";
export * from "./country/actions";
export * from "./city/actions";
export * from "./auth/actions";
