/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const LOGIN_USER_DATA = "LOGIN_USER_DATA";



/* TODOAPP*/
export const TODO_GET_LIST = "TODO_GET_LIST";
export const TODO_GET_LIST_SUCCESS = "TODO_GET_LIST_SUCCESS";
export const TODO_GET_LIST_ERROR = "TODO_GET_LIST_ERROR";
export const TODO_GET_LIST_WITH_FILTER = "TODO_GET_LIST_WITH_FILTER";
export const TODO_GET_LIST_WITH_ORDER = "TODO_GET_LIST_WITH_ORDER";
export const TODO_GET_LIST_SEARCH = "TODO_GET_LIST_SEARCH";
export const TODO_ADD_ITEM = "TODO_ADD_ITEM";
export const TODO_ADD_ITEM_SUCCESS = "TODO_ADD_ITEM_SUCCESS";
export const TODO_ADD_ITEM_ERROR = "TODO_ADD_ITEM_ERROR";
export const TODO_SELECTED_ITEMS_CHANGE = "TODO_SELECTED_ITEMS_CHANGE";

/*religion*/
export const RELIGION_GET_LIST = "RELIGION_GET_LIST";
export const RELIGION_GET_LIST_SUCCESS = "RELIGION_GET_LIST_SUCCESS";
export const RELIGION_GET_LIST_ERROR = "RELIGION_GET_LIST_ERROR";
export const RELIGION_ADD_ITEM = "RELIGION_ADD_ITEM";
export const RELIGION_ADD_ITEM_SUCCESS = "RELIGION_ADD_ITEM_SUCCESS";
export const RELIGION_ADD_ITEM_ERROR = "RELIGION_ADD_ITEM_ERROR";
export const RELIGION_DELETE_ITEM = "RELIGION_DELETE_ITEM";
export const RELIGION_DELETE_SUCCESS = "RELIGION_DELETE_SUCCESS";
export const RELIGION_DELETE_ITEM_ERROR = "RELIGION_DELETE_ITEM_ERROR";
export const RELIGION_UPDATE_ITEM = "RELIGION_UPDATE_ITEM";
export const RELIGION_UPDATE_ITEM_SUCCESS = "RELIGION_UPDATE_ITEM_SUCCESS";
export const RELIGION_UPDATE_ITEM_ERROR = "RELIGION_UPDATE_ITEM_ERROR";
export const RELIGION_DELETE_CHECK = "RELIGION_DELETE_CHECK";







/*deduction */
export const DEDUCTION_GET_LIST = "DEDUCTION_GET_LIST";
export const DEDUCTION_GET_LIST_SUCCESS = "DEDUCTION_GET_LIST_SUCCESS";
export const DEDUCTION_GET_LIST_ERROR = "DEDUCTION_GET_LIST_ERROR";
export const DEDUCTION_ADD_ITEM = "DEDUCTION_ADD_ITEM";
export const DEDUCTION_ADD_ITEM_SUCCESS = "DEDUCTION_ADD_ITEM_SUCCESS";
export const DEDUCTION_ADD_ITEM_ERROR = "DEDUCTION_ADD_ITEM_ERROR";
export const DEDUCTION_DELETE_ITEM = "DEDUCTION_DELETE_ITEM";
export const DEDUCTION_DELETE_SUCCESS = "DEDUCTION_DELETE_SUCCESS";
export const DEDUCTION_DELETE_ITEM_ERROR = "DEDUCTION_DELETE_ITEM_ERROR";
export const DEDUCTION_UPDATE_ITEM = "DEDUCTION_UPDATE_ITEM";
export const DEDUCTION_UPDATE_ITEM_SUCCESS = "DEDUCTION_UPDATE_ITEM_SUCCESS";
export const DEDUCTION_UPDATE_ITEM_ERROR = "DEDUCTION_UPDATE_ITEM_ERROR";
export const DEDUCTION_DELETE_CHECK = "DEDUCTION_DELETE_CHECK";

/*modification type */
export const MODIFICATIONTYPE_GET_LIST = "MODIFICATIONTYPE_GET_LIST";
export const MODIFICATIONTYPE_GET_LIST_SUCCESS = "MODIFICATIONTYPE_GET_LIST_SUCCESS";
export const MODIFICATIONTYPE_GET_LIST_ERROR = "MODIFICATIONTYPE_GET_LIST_ERROR";
export const MODIFICATIONTYPE_ADD_ITEM = "MODIFICATIONTYPE_ADD_ITEM";
export const MODIFICATIONTYPE_ADD_ITEM_SUCCESS = "MODIFICATIONTYPE_ADD_ITEM_SUCCESS";
export const MODIFICATIONTYPE_ADD_ITEM_ERROR = "MODIFICATIONTYPE_ADD_ITEM_ERROR";
export const MODIFICATIONTYPE_DELETE_ITEM = "MODIFICATIONTYPE_DELETE_ITEM";
export const MODIFICATIONTYPE_DELETE_SUCCESS = "MODIFICATIONTYPE_DELETE_SUCCESS";
export const MODIFICATIONTYPE_DELETE_ITEM_ERROR = "MODIFICATIONTYPE_DELETE_ITEM_ERROR";
export const MODIFICATIONTYPE_UPDATE_ITEM = "MODIFICATIONTYPE_UPDATE_ITEM";
export const MODIFICATIONTYPE_UPDATE_ITEM_SUCCESS = "MODIFICATIONTYPE_UPDATE_ITEM_SUCCESS";
export const MODIFICATIONTYPE_UPDATE_ITEM_ERROR = "MODIFICATIONTYPE_UPDATE_ITEM_ERROR";
export const MODIFICATIONTYPE_DELETE_CHECK = "MODIFICATIONTYPE_DELETE_CHECK";

/*currencies type */
export const CURRENCIESTYPE_GET_LIST = " CURRENCIESTYPE_GET_LIST";
export const CURRENCIESTYPE_GET_LIST_SUCCESS = " CURRENCIESTYPE_GET_LIST_SUCCESS";
export const CURRENCIESTYPE_GET_LIST_ERROR = " CURRENCIESTYPE_GET_LIST_ERROR";
export const CURRENCIESTYPE_ADD_ITEM = " CURRENCIESTYPE_ADD_ITEM";
export const CURRENCIESTYPE_ADD_ITEM_SUCCESS = " CURRENCIESTYPE_ADD_ITEM_SUCCESS";
export const CURRENCIESTYPE_ADD_ITEM_ERROR = " CURRENCIESTYPE_ADD_ITEM_ERROR";
export const CURRENCIESTYPE_DELETE_ITEM = " CURRENCIESTYPE_DELETE_ITEM";
export const CURRENCIESTYPE_DELETE_SUCCESS = " CURRENCIESTYPE_DELETE_SUCCESS";
export const CURRENCIESTYPE_DELETE_ITEM_ERROR = " CURRENCIESTYPE_DELETE_ITEM_ERROR";
export const CURRENCIESTYPE_UPDATE_ITEM = " CURRENCIESTYPE_UPDATE_ITEM";
export const CURRENCIESTYPE_UPDATE_ITEM_SUCCESS = " CURRENCIESTYPE_UPDATE_ITEM_SUCCESS";
export const CURRENCIESTYPE_UPDATE_ITEM_ERROR = " CURRENCIESTYPE_UPDATE_ITEM_ERROR";
export const CURRENCIESTYPE_DELETE_CHECK = " CURRENCIESTYPE_DELETE_CHECK";

/*section */
export const SECTION_GET_LIST = " SECTION_GET_LIST";
export const SECTION_GET_LIST_SUCCESS = " SECTION_GET_LIST_SUCCESS";
export const SECTION_GET_LIST_ERROR = " SECTION_GET_LIST_ERROR";
export const SECTION_ADD_ITEM = " SECTION_ADD_ITEM";
export const SECTION_ADD_ITEM_SUCCESS = " SECTION_ADD_ITEM_SUCCESS";
export const SECTION_ADD_ITEM_ERROR = " SECTION_ADD_ITEM_ERROR";
export const SECTION_DELETE_ITEM = " SECTION_DELETE_ITEM";
export const SECTION_DELETE_SUCCESS = " SECTION_DELETE_SUCCESS";
export const SECTION_DELETE_ITEM_ERROR = " SECTION_DELETE_ITEM_ERROR";
export const SECTION_UPDATE_ITEM = " SECTION_UPDATE_ITEM";
export const SECTION_UPDATE_ITEM_SUCCESS = " SECTION_UPDATE_ITEM_SUCCESS";
export const SECTION_UPDATE_ITEM_ERROR = " SECTION_UPDATE_ITEM_ERROR";
export const SECTION_DELETE_CHECK = " SECTION_DELETE_CHECK";


/*cost center*/
export const COSTCENTER_GET_LIST = " COSTCENTER_GET_LIST";
export const COSTCENTER_GET_LIST_SUCCESS = " COSTCENTER_GET_LIST_SUCCESS";
export const COSTCENTER_GET_LIST_ERROR = " COSTCENTER_GET_LIST_ERROR";
export const COSTCENTER_ADD_ITEM = " COSTCENTER_ADD_ITEM";
export const COSTCENTER_ADD_ITEM_SUCCESS = " COSTCENTER_ADD_ITEM_SUCCESS";
export const COSTCENTER_ADD_ITEM_ERROR = " COSTCENTER_ADD_ITEM_ERROR";
export const COSTCENTER_DELETE_ITEM = " COSTCENTER_DELETE_ITEM";
export const COSTCENTER_DELETE_SUCCESS = " COSTCENTER_DELETE_SUCCESS";
export const COSTCENTER_DELETE_ITEM_ERROR = " COSTCENTER_DELETE_ITEM_ERROR";
export const COSTCENTER_UPDATE_ITEM = " COSTCENTER_UPDATE_ITEM";
export const COSTCENTER_UPDATE_ITEM_SUCCESS = " COSTCENTER_UPDATE_ITEM_SUCCESS";
export const COSTCENTER_UPDATE_ITEM_ERROR = " COSTCENTER_UPDATE_ITEM_ERROR";
export const COSTCENTER_DELETE_CHECK = " COSTCENTER_DELETE_CHECK";

/*percentage*/
export const PERCENTAGE_GET_LIST = " PERCENTAGE_GET_LIST";
export const PERCENTAGE_GET_LIST_SUCCESS = " PERCENTAGE_GET_LIST_SUCCESS";
export const PERCENTAGE_GET_LIST_ERROR = " PERCENTAGE_GET_LIST_ERROR";
export const PERCENTAGE_ADD_ITEM = " PERCENTAGE_ADD_ITEM";
export const PERCENTAGE_ADD_ITEM_SUCCESS = " PERCENTAGE_ADD_ITEM_SUCCESS";
export const PERCENTAGE_ADD_ITEM_ERROR = " PERCENTAGE_ADD_ITEM_ERROR";
export const PERCENTAGE_DELETE_ITEM = " PERCENTAGE_DELETE_ITEM";
export const PERCENTAGE_DELETE_SUCCESS = " PERCENTAGE_DELETE_SUCCESS";
export const PERCENTAGE_DELETE_ITEM_ERROR = " PERCENTAGE_DELETE_ITEM_ERROR";
export const PERCENTAGE_UPDATE_ITEM = " PERCENTAGE_UPDATE_ITEM";
export const PERCENTAGE_UPDATE_ITEM_SUCCESS = " PERCENTAGE_UPDATE_ITEM_SUCCESS";
export const PERCENTAGE_UPDATE_ITEM_ERROR = " PERCENTAGE_UPDATE_ITEM_ERROR";
export const PERCENTAGE_DELETE_CHECK = " PERCENTAGE_DELETE_CHECK";


export * from "./menu/actions";
export * from "./settings/actions";

export * from "./auth/actions";
export * from "./religion/actions";

export * from "./deduction/actions";
export * from "./modification_type/actions";
export * from "./currencies_type/actions";
export * from "./section/actions";
export * from "./costcenter/actions";
export * from "./percentage/actions";

// export * from "./documenttype/actions";
